services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-erp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-erp_pass}
      POSTGRES_DB: ${POSTGRES_DB:-erp_db}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-erp_user} -d ${POSTGRES_DB:-erp_db}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    ports:
      - "${API_HOST_PORT:-8000}:8000"
    volumes:
      - .:/app
      - uploads_data:/app/static/uploads

volumes:
  db_data:
  uploads_data:
