"""add is_active column to users

Revision ID: e576b04091b6
Revises: 5bd306f33b2b
Create Date: 2025-07-20 16:35:15.652556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e576b04091b6'
down_revision: Union[str, Sequence[str], None] = '5bd306f33b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('documents', schema=None) as batch_op:
     batch_op.alter_column('intervention_id',
         existing_type=sa.INTEGER(),
         nullable=False)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
     batch_op.alter_column('intervention_id',
         existing_type=sa.INTEGER(),
         nullable=False)
     batch_op.alter_column('user_id',
         existing_type=sa.INTEGER(),
         nullable=False)
    with op.batch_alter_table('plannings', schema=None) as batch_op:
     batch_op.alter_column('equipement_id',
         existing_type=sa.INTEGER(),
         nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'is_active')
    with op.batch_alter_table('plannings', schema=None) as batch_op:
     batch_op.alter_column('equipement_id',
         existing_type=sa.INTEGER(),
         nullable=True)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
     batch_op.alter_column('user_id',
         existing_type=sa.INTEGER(),
         nullable=True)
     batch_op.alter_column('intervention_id',
         existing_type=sa.INTEGER(),
         nullable=True)
    with op.batch_alter_table('documents', schema=None) as batch_op:
     batch_op.alter_column('intervention_id',
         existing_type=sa.INTEGER(),
         nullable=True)
    # ### end Alembic commands ###
