name: Performance Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  performance:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: erp_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U test_user -d erp_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install locust

      - name: Set up test database
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/erp_test
        run: |
          python -c "
          from app.db.database import engine
          from app.models import Base
          Base.metadata.create_all(bind=engine)
          print('Test database initialized')
          "

      - name: Seed test data
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/erp_test
        run: |
          python scripts/seed_data.py

      - name: Start application
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/erp_test
          SECRET_KEY: test-secret-key
          FILES_ENC_KEY: test-fernet-key
          DEBUG: true
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Run Locust performance test
        run: |
          locust -f scripts/locustfile.py --headless --users 50 --spawn-rate 5 --run-time 2m --host http://localhost:8000

      - name: Generate performance report
        run: |
          echo "Performance test completed"
          # Add report generation logic here
