name: Security Scan

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    # Run weekly on Sundays
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pip-audit

      - name: Run Bandit security scan
        run: |
          bandit -r app -f json -o bandit-report.json || true
          cat bandit-report.json

      - name: Run Safety vulnerability scan
        run: |
          safety check --json > safety-report.json || true
          cat safety-report.json

      - name: Run pip-audit
        run: |
          pip-audit -f json > pip-audit-report.json || true
          cat pip-audit-report.json

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
            pip-audit-report.json
